urls:
  - url: "/specs/openapi.AuthApi.yaml"
    name: "Auth API"
  - url: "/specs/openapi.UserApi.yaml"
    name: "User API"
  - url: "/specs/openapi.UserSkillApi.yaml"
    name: "User Skill API"
  - url: "/specs/openapi.SkillCategoryApi.yaml"
    name: " Skill Category API"
  - url: "/specs/openapi.SkillApi.yaml"
    name: "Skill API"
